# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(f_name:"test", l_name:"test", email:"test2@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test3@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test4@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test5@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test6@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test7@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test8@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test9@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test10@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test11@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test12@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test13@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test14@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test15@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test16@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test17@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test18@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test19@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test20@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test21@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test22@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test23@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test24@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test25@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test26@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test27@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test28@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test29@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test30@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test31@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test32@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test33@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test34@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test35@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test36@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test37@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test38@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test39@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test40@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test41@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test42@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test43@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test44@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test45@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test46@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test47@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test48@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test49@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test50@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test51@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test52@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test53@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test54@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test55@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test56@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test57@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test58@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test59@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test60@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test61@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test62@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test63@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test64@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test65@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)
User.create(f_name:"test", l_name:"test", email:"test66@test.com", password:"testtest", password_confirmation:"testtest", user_role:0, company_id:1)